### ISSUE TITLE
Sometimes Wechaty can't login (with puppeteer)

### ISSUE THREAD

**Issue by github-liuzhao** [Chatie/wechaty#899] opened 2017-10-19 12:31 UTC
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
beijing
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?

node version : v7.4.0
code: $ WECHATY_LOG=silly node dist/mybot.js

after scan
```shell
20:22:30 SILL PuppetWebEvent onUnload()
20:22:30 SILL StateSwitch Puppet:target() is live
20:22:30 SILL StateSwitch Puppet:current() is live
20:22:30 SILL StateSwitch Puppet:stable() is true
20:22:30 VERB PuppetWeb quit() state target(live) current(live) stable(true)
20:22:30 SILL StateSwitch Puppet:current() is live
20:22:30 VERB PuppetWeb quit() make watchdog sleep before do quit
20:22:30 VERB StateSwitch Puppet:target(dead) <- (live)
20:22:30 VERB StateSwitch Puppet:current(dead,false) <- (live,true)
20:22:30 VERB PuppetWebBridge quit()
20:22:30 SILL PuppetWebBridge quit() page.close()-ed
20:22:30 SILL PuppetWebBridge quit() browser.close()-ed
20:22:30 VERB StateSwitch Puppet:current(dead,true) <- (dead,false)
20:22:30 VERB PuppetWeb init() with Profile<null>
20:22:30 VERB StateSwitch Puppet:target(live) <- (dead)
20:22:30 VERB StateSwitch Puppet:current(live,false) <- (dead,true)
20:22:30 VERB PuppetWeb initWatchdogForPuppet()
20:22:30 VERB PuppetWeb initWatchdogForScan()
20:22:30 VERB PuppetWeb initBridge()
20:22:30 SILL StateSwitch Puppet:target() is live
20:22:30 VERB PuppetWebBridge constructor()
20:22:30 VERB PuppetWebBridge init()
20:22:30 VERB PuppetWebBridge initBrowser()
20:22:30 VERB PUppetWebBridge initBrowser() version: HeadlessChrome/64.0.3240.0
20:22:30 VERB PuppetWebBridge init() initBrowser() done
20:22:30 VERB PuppetWebBridge initPage()
20:22:30 VERB Profile get(cookies)
20:22:30 VERB PuppetWebBridge cookieDomain([object Object],[object Object],[object Object])
20:22:30 SILL PuppetWebBridge cookieDomain() no valid cookie, return default hostname
20:22:30 VERB PuppetWebBridge initPage() before page.goto(url)
20:22:31 VERB PuppetWebBridge initPage() after page.goto(url)
20:22:31 SILL PuppetWebBridge initPage() page.setCookie() 3 cookies set back
20:22:32 VERB PuppetWebBridge init() initPage() done
20:22:32 VERB PuppetWebBridge readyAngular()
20:22:32 VERB PuppetWebBridge readyAngular() Promise.resolve()
20:22:32 VERB PuppetWebBridge inject()
20:22:32 SILL PuppetWebBridge inject() eval(Wechaty) return code[200] message[WechatyBro Inject Done]
20:22:32 SILL PuppetWebBridge proxyWechaty(init)
20:22:32 SILL PuppetWebBridge inject() Wechaty.init() return code[200] message[WechatyBro Init Succ]
20:22:32 VERB PuppetWebBridge ding(inject() OK!)
20:22:32 SILL PuppetWebBridge proxyWechaty(ding , inject() OK!)
20:22:32 SILL PuppetWebBridge inject() ding success
20:22:32 VERB PuppetWeb initBridge() done
20:22:32 VERB PuppetWebBridge clickSwitchAccount()
20:22:32 SILL PuppetWebBridge clickSwitchAccount() button not found
20:22:32 VERB StateSwitch Puppet:current(live,true) <- (live,false)
20:22:32 SILL PuppetWeb initWatchdogForPuppet() dog.on(feed)
20:22:32 SILL Wechaty memoryCheck() free: 180 MB, require: 4 MB
20:22:32 SILL PuppetWeb initWatchdogForPuppet() dog.on(feed)
20:22:32 SILL Wechaty memoryCheck() free: 180 MB, require: 4 MB
20:22:32 VERB RxQueue constructor(type=throttle, time=300000)
20:22:32 VERB PuppetWeb init() done
20:24:32 WARN PuppetWeb initWatchdogForPuppet() dog.on(reset) last food: inited
20:24:32 SILL StateSwitch Puppet:target() is live
20:24:32 SILL StateSwitch Puppet:current() is live
20:24:32 SILL StateSwitch Puppet:stable() is true
20:24:32 VERB PuppetWeb quit() state target(live) current(live) stable(true)
20:24:32 SILL StateSwitch Puppet:current() is live
20:24:32 VERB PuppetWeb quit() make watchdog sleep before do quit
20:24:32 VERB StateSwitch Puppet:target(dead) <- (live)
20:24:32 VERB StateSwitch Puppet:current(dead,false) <- (live,true)
20:24:32 VERB PuppetWebBridge quit()
20:24:32 SILL PuppetWebBridge quit() page.close()-ed
20:24:32 SILL PuppetWebBridge quit() browser.close()-ed
20:24:32 VERB StateSwitch Puppet:current(dead,true) <- (dead,false)
20:24:32 VERB PuppetWeb init() with Profile<null>
20:24:32 VERB StateSwitch Puppet:target(live) <- (dead)
20:24:32 VERB StateSwitch Puppet:current(live,false) <- (dead,true)
20:24:32 VERB PuppetWeb initWatchdogForPuppet()
20:24:32 VERB PuppetWeb initWatchdogForScan()
20:24:32 VERB PuppetWeb initBridge()
20:24:32 SILL StateSwitch Puppet:target() is live
20:24:32 VERB PuppetWebBridge constructor()
20:24:32 VERB PuppetWebBridge init()
20:24:32 VERB PuppetWebBridge initBrowser()
20:24:32 VERB PUppetWebBridge initBrowser() version: HeadlessChrome/64.0.3240.0
20:24:32 VERB PuppetWebBridge init() initBrowser() done
20:24:32 VERB PuppetWebBridge initPage()
20:24:32 VERB Profile get(cookies)
20:24:32 VERB PuppetWebBridge cookieDomain([object Object],[object Object],[object Object])
20:24:32 SILL PuppetWebBridge cookieDomain() no valid cookie, return default hostname
20:24:32 VERB PuppetWebBridge initPage() before page.goto(url)
20:24:33 VERB PuppetWebBridge initPage() after page.goto(url)
20:24:33 SILL PuppetWebBridge initPage() page.setCookie() 3 cookies set back
20:24:33 VERB PuppetWebBridge init() initPage() done
20:24:33 VERB PuppetWebBridge readyAngular()
20:24:33 VERB PuppetWebBridge readyAngular() Promise.resolve()
20:24:33 VERB PuppetWebBridge inject()
20:24:33 SILL PuppetWebBridge inject() eval(Wechaty) return code[200] message[WechatyBro Inject Done]
20:24:33 SILL PuppetWebBridge proxyWechaty(init)
20:24:33 SILL PuppetWebBridge inject() Wechaty.init() return code[200] message[WechatyBro Init Succ]
20:24:33 VERB PuppetWebBridge ding(inject() OK!)
20:24:33 SILL PuppetWebBridge proxyWechaty(ding , inject() OK!)
20:24:33 SILL PuppetWebBridge inject() ding success
20:24:33 VERB PuppetWeb initBridge() done
20:24:33 VERB PuppetWebBridge clickSwitchAccount()
20:24:33 SILL PuppetWebBridge clickSwitchAccount() button not found
20:24:33 VERB StateSwitch Puppet:current(live,true) <- (live,false)
20:24:33 SILL PuppetWeb initWatchdogForPuppet() dog.on(feed)
20:24:33 SILL Wechaty memoryCheck() free: 138 MB, require: 4 MB
20:24:33 SILL PuppetWeb initWatchdogForPuppet() dog.on(feed)
20:24:33 SILL Wechaty memoryCheck() free: 138 MB, require: 4 MB
20:24:33 SILL PuppetWeb initWatchdogForPuppet() dog.on(feed)
20:24:33 SILL Wechaty memoryCheck() free: 138 MB, require: 4 MB
20:24:33 VERB RxQueue constructor(type=throttle, time=300000)
20:24:33 VERB PuppetWeb init() done
```

**Comment by GeoffZhu** [comment] 2017-10-20 06:27
+1

**Comment by zixia** [comment] 2017-10-23 05:03
The problem is related with the new `puppeteer`: it's too fast to emit the `scan` event, before we are ready for that.

This issue should have been fixed in version v0.11.4 or above, please let me know if you have any issue with it.

@github-liuzhao @GeoffZhu @xwxtwd @Randyedu @wangqi0316

**Comment by xwxtwd** [comment] 2017-10-23 09:35
@zixia it's ok now. thx~

**Comment by zixia** [comment] 2017-10-23 17:16
Could there anyone help me to confirm this?

I'll close this issue after one more confirmation.

**Comment by wangqi0316** [comment] 2017-10-23 17:21
Confirmed 0.11.7 works fine.

**Comment by zixia** [comment] 2017-10-23 17:33
@wangqi0316 Thank you very much!

I'll close this issue for now, and please feel free to let me know if there are any other issues.

**Closed by zixia** 2017-10-23 17:33 UTC
Labels: bug
