### ISSUE TITLE
在 websocket 的回调中无法使用 wechaty 吗

### ISSUE THREAD

**Issue by cmzz** [Chatie/wechaty#665] opened 2017-07-17 14:24 UTC
```
this.ws.on('message', (message) => {
      if ( wechaty 已登录 ) {
        Room.find({topic: 'test'})
          .then((to) => {
            to.say('hi')
          })
      }
    })
```

上面的代码无法运行， 错误：
```
[22:20:38:0410] [error] TypeError: __WEBPACK_IMPORTED_MODULE_6_wechaty___default.a.find is not a function
      at WebSocket.<anonymous> (/Users/steve/www/electron-projects/new-pigtk-client/dist/electron/main.js:107577:59)
      at emitTwo (events.js:106:13)
      at WebSocket.emit (events.js:194:7)
      at Receiver._receiver.onmessage (/Users/steve/www/electron-projects/new-pigtk-client/node_modules/.2.3.1@ws/lib/WebSocket.js:146:54)
      at Receiver.dataMessage (/Users/steve/www/electron-projects/new-pigtk-client/node_modules/.2.3.1@ws/lib/Receiver.js:389:14)
      at Receiver.getData (/Users/steve/www/electron-projects/new-pigtk-client/node_modules/.2.3.1@ws/lib/Receiver.js:330:12)
      at Receiver.startLoop (/Users/steve/www/electron-projects/new-pigtk-client/node_modules/.2.3.1@ws/lib/Receiver.js:165:16)
      at Receiver.add (/Users/steve/www/electron-projects/new-pigtk-client/node_modules/.2.3.1@ws/lib/Receiver.js:139:10)
      at Socket._ultron.on (/Users/steve/www/electron-projects/new-pigtk-client/node_modules/.2.3.1@ws/lib/WebSocket.js:142:22)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:191:7)
      at readableAddChunk (_stream_readable.js:178:18)
      at Socket.Readable.push (_stream_readable.js:136:10)
      at TCP.onread (net.js:560:20)

[22:20:38:0741] [info] Bot bot logout.
```

**Comment by cmzz** [comment] 2017-07-17 14:29
@zixia Need your help !

**Comment by zixia** [comment] 2017-07-17 16:48
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by zixia** [comment] 2017-08-18 03:13
Hope you had resolved your problem. I'll close this issue because there's not enough information about the question.

**Closed by zixia** 2017-08-18 03:13 UTC
