### ISSUE TITLE
登录不了一个错误报告

### ISSUE THREAD

**Issue by lb1938** [Chatie/wechaty#1841] opened 2019-08-18 02:20 UTC
重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

0. 发 Issue 指南
请运行下面的命令，看问题是否可以被解决：
rm -rf package-lock.json
rm -rf node_modules
npm install
请在 FAQ 清单 看是否已有解决办法。

请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

1. 提供你的包版本信息
wechaty 版本：0.22.1
wechaty-puppet-padpro 版本：0.0.58
node 版本： 10.15.3
你使用的操作系统：CentOS
2. Bug 描述
无法登录

错误堆栈
11:03:37 WARN sendShort receive unknown package: [90] 5a06fffffff3000000000000000000008b0100000000 Z�����]
11:03:37 ERR WechatGateway Error happened when call api: GrpcNewInit, params: undefined
undefined
11:03:37 WARN Error happened when calling GrpcNewInit: TypeError: Cannot read property 'forEach' of null
at PadproManager. (/home/wechatbot/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:379:22)
at Generator.next ()
at /home/wechatbot/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:7:71
at new Promise ()
at __awaiter (/home/wechatbot/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:3:12)
at PadproManager.processMessages (/home/wechatbot/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:378:16)
at PadproManager. (/home/wechatbot/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:119:28)
at Generator.next ()
at fulfilled (/home/wechatbot/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:4:58)
at process._tickCallback (internal/process/next_tick.js:68:7)

同样的环境下 换了个token又可以运行了 唯独那个token运行就会报错

3. 复现的步骤 (或者解决的步骤)
扫码登陆之后即会出现这个错误

4. 期待程序运行的结果
请用精简的语言描述你期待运行的结果

5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（请不要在这里粘贴日志截图）

6. 完整的日志信息：
11:13:53 SILL Accessory #0 constructor()
11:13:53 VERB Wechaty contructor()
11:13:53 VERB StateSwitch constructor(name=Wechaty)
11:13:53 VERB StateSwitch constructor(name=WechatyReady)
11:13:53 VERB Wechaty on(scan, function) registered
11:13:53 VERB Wechaty onFunction(scan)
11:13:53 VERB Wechaty on(login, function) registered
11:13:53 VERB Wechaty onFunction(login)
11:13:53 VERB Wechaty on(message, function) registered
11:13:53 VERB Wechaty onFunction(message)
11:13:53 SILL Wechaty version() form development environment is not availble: ENOENT: no such file or directory, stat '/home/wechatbot/node_modules/wechaty@0.22.6@wechaty/dist/.git'
11:13:53 INFO Wechaty <Puppet#0()/PuppetPadpro#0> start() v0.22.6 is starting...
11:13:53 VERB Wechaty puppet: Puppet#0()/PuppetPadpro#0
11:13:53 VERB Wechaty profile: undefined
11:13:53 VERB Wechaty id: cjzgec0fp0000xmp5f41jb1cb
11:13:53 SILL StateSwitch on() is false
11:13:53 SILL StateSwitch off() is true
11:13:53 VERB StateSwitch off(true) <- (true)
11:13:53 SILL StateSwitch on() is false
11:13:53 VERB StateSwitch on(pending) <- (false)
11:13:53 VERB MemoryCard constructor(undefined)
11:13:53 VERB MemoryCard getStorage() for storage type: N/A
11:13:53 VERB MemoryCard load() from storage: N/A
11:13:53 VERB MemoryCard load() no storage
11:13:53 VERB Puppet constructor() memory.load() done
11:13:53 VERB Wechaty initPuppet() Puppet#0()/PuppetPadpro#0
11:13:53 VERB MemoryCard multiplex(puppet)
11:13:53 VERB MemoryCard static multiplex(MemoryCard<>, puppet)
11:13:53 VERB MemoryCard constructor({"multiplex":{"name":"puppet","parent":{"payload":{},"multiplexNameList":[]}}})
11:13:53 VERB PuppetManager resolve({wechaty: Wechaty#cjzgec0fp0000xmp5f41jb1cb<Puppet#0()/PuppetPadpro#0>(), puppet: Puppet#0()/PuppetPadpro#0, puppetOptions: undefined})
11:13:53 VERB PuppetManager resolveInstance(Puppet#0()/PuppetPadpro#0)
11:13:53 VERB Puppet setMemory()
11:13:53 VERB Wechaty initPuppetEventBridge(Puppet#0()/PuppetPadpro#0)
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(login) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(logout) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(message) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(scan) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(dong) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(error) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(ready) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(reset) registered
11:13:53 VERB Wechaty initPuppetEventBridge() puppet.on(watchdog) registered
11:13:53 VERB Wechaty initAccessory(Puppet#0()/PuppetPadpro#0)
11:13:53 SILL Accessory static set wechaty = "Wechaty#cjzgec0fp0000xmp5f41jb1cb<Puppet#0()/PuppetPadpro#0>()"
11:13:53 SILL Accessory static set wechaty = "Wechaty#cjzgec0fp0000xmp5f41jb1cb<Puppet#0()/PuppetPadpro#0>()"
11:13:53 SILL Accessory static set wechaty = "Wechaty#cjzgec0fp0000xmp5f41jb1cb<Puppet#0()/PuppetPadpro#0>()"
11:13:53 SILL Accessory static set wechaty = "Wechaty#cjzgec0fp0000xmp5f41jb1cb<Puppet#0()/PuppetPadpro#0>()"
11:13:53 SILL Accessory static set wechaty = "Wechaty#cjzgec0fp0000xmp5f41jb1cb<Puppet#0()/PuppetPadpro#0>()"
11:13:53 SILL Accessory static set wechaty = "Wechaty#cjzgec0fp0000xmp5f41jb1cb<Puppet#0()/PuppetPadpro#0>()"
11:13:53 SILL Accessory static set puppet = "Puppet#0()/PuppetPadpro#0"
11:13:53 SILL Accessory static set puppet = "Puppet#0()/PuppetPadpro#0"
11:13:53 SILL Accessory static set puppet = "Puppet#0()/PuppetPadpro#0"
11:13:53 SILL Accessory static set puppet = "Puppet#0()/PuppetPadpro#0"
11:13:53 SILL Accessory static set puppet = "Puppet#0()/PuppetPadpro#0"
11:13:53 SILL Accessory static set puppet = "Puppet#0()/PuppetPadpro#0"
11:13:53 SILL Accessory set puppet = "Puppet#0()/PuppetPadpro#0"
11:13:53 SILL StateSwitch on() is false
11:13:53 SILL StateSwitch on() is false
11:13:53 VERB StateSwitch on(pending) <- (false)
11:13:53 INFO WechatGateway init(*******************, padpro.botorange.com:6666, undefined)
11:13:53 SILL StateSwitch off() is false
11:13:53 SILL StateSwitch on() is pending
11:13:53 VERB StateSwitch on(true) <- (pending)
11:13:53 VERB Wechaty on(heartbeat, function) registered
11:13:53 VERB Wechaty onFunction(heartbeat)
11:13:53 SILL StateSwitch on() is pending
11:13:53 VERB StateSwitch on(true) <- (pending)
11:13:53 INFO WechatGateway initLongSocket() connected to wechat long host server: long.weixin.qq.com.
11:13:53 SILL Wechaty memoryCheck() free: 504 MB, require: 4 MB
Scan QR Code to login: 0
https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fweixin.qq.com%2Fx%2FgZjS2a4vGeie87qV9Be1
Scan QR Code to login: 1
https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fweixin.qq.com%2Fx%2FgZjS2a4vGeie87qV9Be1
Scan QR Code to login: 2
https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fweixin.qq.com%2Fx%2FgZjS2a4vGeie87qV9Be1
11:14:13 INFO PadproGrpc GrpcQRCodeLogin(wxid**********, extdevnewpwd_CiNBeGNCdlZicE04R2lNUFpCNUhkNDRydmdAcXJ0aWNrZXRfMBJARU9IQjF6WUJhaWczczNXVTNDYW1tTmJtQjBQYjlyTjVtWUJ4bEhJYk9uVWFxaVp3OG4xanNOMC1mQ0VnbUJZeRoYZ1NlSjc4TW5pa0NlYnhleFJxLVlzaHNS)
11:14:13 INFO WechatGateway initLongSocket() connected to wechat long host server: 163.177.81.141.
11:14:14 INFO CacheManager init()
11:14:14 WARN sendShort receive unknown package: [90] 5a06fffffff3000000000000000000008b0100000000 Z�����]
11:14:14 ERR WechatGateway Error happened when call api: GrpcNewInit, params: undefined
undefined
11:14:14 WARN Error happened when calling GrpcNewInit: TypeError: Cannot read property 'forEach' of null
at PadproManager. (/home/wechatbot/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:379:22)
at Generator.next ()
at /home/wechatbot/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:7:71
at new Promise ()
at __awaiter (/home/wechatbot/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:3:12)
at PadproManager.processMessages (/home/wechatbot/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:378:16)
at PadproManager. (/home/wechatbot/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:119:28)
at Generator.next ()
at fulfilled (/home/wechatbot/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/padpro-manager.js:4:58)
at process._tickCallback (internal/process/next_tick.js:68:7)

7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment] 2019-08-19 07:12
@lb1938 再次启动这个bot还是会报同样的错么？

**Comment by lb1938** [comment] 2019-08-19 07:17
> @lb1938 再次启动这个bot还是会报同样的错么？

不会了，不罢工了，目前正常.

**Comment by lijiarui** [comment] 2019-08-21 08:57
Close this since it cannot reproduce.

**Closed by lijiarui** 2019-08-21 08:57 UTC
Labels: puppet specific

**Comment by lb1938** [comment] 2019-08-21 09:03
不行呢 还是登录不了 提示异地登录

**Comment by lijiarui** [comment] 2019-08-21 13:44
异地登陆是近期正在解决的问题。所有账号都出现了这个问题。

**Comment by llh1187** [comment] 2020-03-07 05:43
> 异地登陆是近期正在解决的问题。所有账号都出现了这个问题。

现在又不行了哦
