### ISSUE TITLE
@ 人没提示

### ISSUE THREAD

**Issue by AlphaFase** [Chatie/wechaty#1504] opened 2018-07-25 06:06 UTC
pad收费版

**Comment by lijiarui** [comment] 2018-07-25 07:20
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.

**Closed by lijiarui** 2018-07-25 07:20 UTC

**Comment by zixia** [comment] 2018-07-25 07:35
@lijiarui I don't think this issue needs more information because it is very clear that we had not implemented this feature yet.
