### ISSUE TITLE
Send(upload) an image twice will cause error.

### ISSUE THREAD

**Issue by iRabbit** [Chatie/wechaty#422] opened 2017-04-20 02:07 UTC
I tried the MediaMessage.say("path.jpg"),it worked perfect when I send a picture to one contact.
But if I  send a pic to more people ,it dosen't work. 
when upload the same pic more than one times, the MediaId cannot get currectly.

And I suggest that add this function in Room  and Contact class ,same as  say text.

ps: forgive my poor English!

**Comment by zixia** [comment] 2017-04-20 03:22
Hello,

1. You are luck: Room/Contact say(MediaMessage) support had just implemented by @mukaiu by PR https://github.com/Chatie/wechaty/pull/420 , which just merged to the code base at yesterday. 

You can try it by update your docker to the latest version.

2. According to what you had described: 
> when uploading the same pic more than one times, the MediaId cannot get correctly.

I guess this might because Wechat Server does not allow to upload the same media twice in one Session.

I think the solution should be not to upload the same media file twice by caching the MediaId of the Uploaded File and reuse it in the future.

There also has a very interesting project that we could have a look: [微信表情轰炸器](https://github.com/spacelan/wechat-emoticon)

It can send emoticon by MediaId directly, no need to upload anything.

The configuration file is like a md5/mediaId map, which is very useful at here:

https://github.com/spacelan/wechat-emoticon/blob/master/emoticons.json

```json
[
{
  "url": "http://emoji.qpic.cn/wx_emoji/ic6hURX8DEDW5he0vo7kK1YR74EiafuDsezGNwibZU7RA7wXoia6WOs5FQ/",
  "md5": "54fa992dfff691c63879682f3d141e46"
}, {
  "url": "http://emoji.qpic.cn/wx_emoji/aL7ySfk4WblG1giaGl7haADVFpxgZfjhwVR1ycGOVfJ9ickDNTd7QgqQ/",
  "md5": "725019d0ad8622a972052475793ec17d"
},
]
```

@mukaiu How do you think about this?

**Comment by iRabbit** [comment] 2017-04-20 07:01
@zixia  Thanks for your comment.

**Comment by mukaiu** [comment] 2017-04-20 12:46
@iRabbit What is the interval between sending two times?

**Comment by iRabbit** [comment] 2017-04-24 01:25
@mukaiu  I want to send the same image to different contacts, so I think send message in the same times will be better.

In my mind, if the MediaId of  MediaMessage can be remembered  after Image uploaded ,that will be usefull.

**Comment by mukaiu** [comment] 2017-04-25 15:00
@iRabbit I can not reproduce this problem. Can be paste the send code?

**Comment by lijiarui** [comment] 2017-04-25 15:13
@iRabbit I can send the same image to different contacts, it works well, my interval is 1 second

**Comment by mukaiu** [comment] 2017-05-02 15:58
@iRabbit see #439 #470

**Comment by zixia** [comment] 2017-08-18 03:42
@iRabbit I'll close this issue because we have lots of related PR merged recently.

Please feel free to reply to reopen it if you can reproduce the problem with the latest code.

**Closed by zixia** 2017-08-18 03:42 UTC
Labels: bug, enhancement
