### ISSUE TITLE
ERROR: Failed to download Chromium rXXXXXX! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

### ISSUE THREAD

**Issue by francishero** [Chatie/wechaty#867] opened 2017-10-10 17:09 UTC
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
just local development in china
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
none
### Expected behavior

just expects wechaty to install
### Actual behavior
yarn add wechaty
yarn add v1.1.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error C:\Users\Francis\Documents\REACT-JS-SUMMER-17\wechat-bots\node_modules\puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: C:\Users\Francis\Documents\REACT-JS-SUMMER-17\wechat-bots\node_modules\puppeteer
Output:
ERROR: Failed to download Chromium r499413! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:606:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### Steps to reproduce the behavior (and fixes, if any)

windows 10 machine 
mkdir folder-for-project
cd folder-for-project
yarn init 
yarn add wechaty

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:


yarn add v1.1.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠈ puppeteer:     at TLSWrap.onread (net.js:606:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'rea
[-/1] ⠈ waiting...
[-/1] ⠈ waiting...
[-/1] ⠁ waiting...
error c:\Users\Francis\Documents\REACT-JS-SUMMER-17\wechat-bots\node_modules\puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: c:\Users\Francis\Documents\REACT-JS-SUMMER-17\wechat-bots\node_modules\puppeteer
Output:
ERROR: Failed to download Chromium r499413! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
```
</details>

**Comment by zixia** [comment] 2017-10-10 17:13
It was because of the GFW:

```
[1/1] ⠈ puppeteer:     at TLSWrap.onread (net.js:606:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'rea
```

Wechaty needs to download `puppeteer` from a google server. 

You need to make sure your box can connect to Google in order to prevent `errno: 'ECONNRESET'` error.

**Comment by francishero** [comment] 2017-10-10 17:43
But am using a VPN and can use gmail now to reply and also use google

**Comment by zixia** [comment] 2017-10-10 18:12
> "ECONNRESET" means the other side of the TCP conversation abruptly closed its end of the connection. This is most probably due to one or more application protocol errors. You could look at the API server logs to see if it complains about something.

There must be something wrong with your network.

I suggest you try to install puppeteer and see if you could success by:

```shell
$ npm install puppeteer
```

This is an NPM module from google chrome team.

I guess you will still get fail. If so, then this issue is not related with Wechaty.

**Comment by francishero** [comment] 2017-10-10 18:20
ooh yes it fails to install puppeter.

**Comment by zixia** [comment] 2017-10-11 03:27
Ok, so it's confirmed this issue is not related with Wechaty but your local network.

Could you close this issue for now?

**Comment by zixia** [comment] 2017-10-11 03:34
@lijiarui Could you please add this Q/A to our FAQ? Thanks.

**Comment by francishero** [comment] 2017-10-11 07:40
sure

**Closed** 2017-10-11 07:55 UTC
Labels: question

**Comment by charlenezell** [comment] 2018-01-12 10:46
nslookup 
and you can get 
216.58.221.144 storage.googleapis.com

**Comment by newip** [comment] 2018-07-04 07:02
When using ssr for vpn connection, change the mode from "Auto Mode by PAC" to "White List Mode" could possibly solve it.
