### ISSUE TITLE
Some strange log warn

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#336] opened 2017-03-19 03:37 UTC
I'm trying to set alias for the contact, but it occurs some strange error I have nerver saw.

### Steps to reproduce the behavior (and fixes, if any)

Trying to set alias for the contact

### Code
```
 public async addAlias() {
    const uuid = require('uuid/v1')
    const contactList = await Contact.findAll()
    for (let i = 0; i < contactList.length; i++) {
      const contact = contactList[i]
      const aliasId = contact.alias()
      if (!aliasId) {
        const result = await contact.alias(uuid())
        if (result) {
          console.log(`change successful: ${contact.alias()}`)
        }
      }
    }
  }
```

### Paste the full output logs here with `WECHATY_LOG=silly` set
```
11:43:36 WARN PuppetWebBridge execute() exception: ETIMEDOUT connect ETIMEDOUT 127.0.0.1:64117
11:43:36 VERB PuppetWebBridge proxyWechaty(getContact, @d4c76ab4a1b781dbcfe99a7c557e6c23e236d8c87ae6890e2d1f5245fe7ad82b)
11:43:36 WARN PuppetWebBridge proxyWechaty() exception: ETIMEDOUT connect ETIMEDOUT 127.0.0.1:64117
11:43:36 SILL PuppetWebBridge proxyWechaty(getContact, @d4c76ab4a1b781dbcfe99a7c557e6c23e236d8c87ae6890e2d1f5245fe7ad82b) exception: ETIMEDOUT connect ETIMEDOUT 127.0.0.1:64117
11:43:36 SILL PuppetWebBrowser execute() script:  const callback = arguments[arguments.length - 1]
      const isAsync = (typeof callback === 'function')
      return WechatyBro
              .getContact
              .apply(undefined
                      , isAsync
                        ? JSON.parse(decodeURIComponent(window.atob('JTVCJTIyJTQwMTVmNzMxZjA2MTRkMTM4YzJjYTA3OTZiNjg4YjkxNmY3MDdiNmExZGQ0YjVjMzZmNDQxMDI2ZDBkYmQ3ZDc2MCUyMiU1RA=='))).concat(callback)
                        : JSON.parse(decodeURIComponent(window.atob('JTVCJTIyJTQwMTVmNzMxZjA2MTRkMTM4YzJjYTA3OTZiNjg4YjkxNmY3MDdiNmExZGQ0YjVjMzZmNDQxMDI2ZDBkYmQ3ZDc2MCUyMiU1RA==')))
                    )

11:43:36 WARN PuppetWebBrowser execute() exception: ETIMEDOUT connect ETIMEDOUT 127.0.0.1:64117, Error: ETIMEDOUT connect ETIMEDOUT 127.0.0.1:64117
    at ClientRequest.<anonymous> (/Users/lijiarui/Documents/git/robot_ts/node_modules/.3.3.0@selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
11:43:36 WARN PuppetWebBridge execute() exception: ETIMEDOUT connect ETIMEDOUT 127.0.0.1:64117
11:43:36 VERB PuppetWebBridge proxyWechaty(getContact, @15f731f0614d138c2ca0796b688b916f707b6a1dd4b5c36f441026d0dbd7d760)
11:43:36 WARN PuppetWebBridge proxyWechaty() exception: ETIMEDOUT connect ETIMEDOUT 127.0.0.1:64117
11:43:36 SILL PuppetWebBridge proxyWechaty(getContact, @15f731f0614d138c2ca0796b688b916f707b6a1dd4b5c36f441026d0dbd7d760) exception: ETIMEDOUT connect ETIMEDOUT 127.0.0.1:64117
11:43:36 SILL PuppetWebBrowser execute() script:  const callback = arguments[arguments.length - 1]
      const isAsync = (typeof callback === 'function')
      return WechatyBro
              .getContact
              .apply(undefined
                      , isAsync
                        ? JSON.parse(decodeURIComponent(window.atob('JTVCJTIyJTQwMzFmZWE5NTlkNWJmNzAwZGExNDhlNjZjN2NhNGNjNDI5ZWQ4Y2Q3MjA2MTZlZWY3YTc3YWVjNmI3NWEzYzE3NCUyMiU1RA=='))).concat(callback)
                        : JSON.parse(decodeURIComponent(window.atob('JTVCJTIyJTQwMzFmZWE5NTlkNWJmNzAwZGExNDhlNjZjN2NhNGNjNDI5ZWQ4Y2Q3MjA2MTZlZWY3YTc3YWVjNmI3NWEzYzE3NCUyMiU1RA==')))
                    )

11:43:36 WARN PuppetWebBrowser execute() exception: ETIMEDOUT connect ETIMEDOUT 127.0.0.1:64117, Error: ETIMEDOUT connect ETIMEDOUT 127.0.0.1:64117
    at ClientRequest.<anonymous> (/Users/lijiarui/Documents/git/robot_ts/node_modules/.3.3.0@selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by lijiarui** [comment] 2017-03-19 04:08
Then I tried to run the code in docker, error as follows:

```
ERR Room contactGetter(@@884245a40f7d571186585d5a090ca1c16b57181b65152d18531b85f37cb11ed1) exception: Cannot read property 'Symbol(Symbol.iterator)' of undefined
ERR Message ready() exception: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Room.<anonymous> (/bot/node_modules/wechaty/src/room.ts:97:24)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/room.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/room.js:3:12)
    at Room.readyAllMembers (/bot/node_modules/wechaty/dist/src/room.js:51:16)
    at Room.<anonymous> (/bot/node_modules/wechaty/src/room.ts:133:18)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty/dist/src/room.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
ERR PuppetWebEvent onServerMessage() exception: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Room.<anonymous> (/bot/node_modules/wechaty/src/room.ts:97:24)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/dist/src/room.js:7:71
    at __awaiter (/bot/node_modules/wechaty/dist/src/room.js:3:12)
    at Room.readyAllMembers (/bot/node_modules/wechaty/dist/src/room.js:51:16)
    at Room.<anonymous> (/bot/node_modules/wechaty/src/room.ts:133:18)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty/dist/src/room.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
ERR Config ###########################
ERR Config unhandledRejection: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined [object Promise]
ERR Config ###########################
ERR Config unhandledRejection::catch(Cannot read property 'Symbol(Symbol.iterator)' of undefined)
(node:22) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
```

**Comment by zixia** [comment] 2017-03-19 04:23
1. I guess this is a bug when you make calls too quick. 

Can you add a `await Wechaty.instance().sleep(1000)` in your for loop to see if this could prevent the ERR?

2. the reason that log message is different between docker and other environment, I believe is the nodejs version not same.

Docker is using nodejs v7.6(or above). I suggest you upgrade your nodejs to the lastest v7, and try again.

**Comment by lijiarui** [comment] 2017-03-19 04:27
Actually, I add them to a queue, the inveval is 5 second.

code as follows:
```
async function alilas() {
  const contactList = await Contact.findAll()
  for (let i = 0; i < contactList.length; i++) {
    const contact = contactList[i]
    const aliasId = contact.alias()
    if (!aliasId) {
       TaskManager.addTaskFunc( async _ => {
                                  const result = await contact.alias(uuid())
                                  if (result) {
                                    console.log(`change successful: ${contact.alias()}`)
                                  }
                            }, TaskManager.TaskName.REMARK)
    }
  }
}
```
So I guess it is not because the calls too quick.

Yesterday I tried it, the same environment but all works well, today it occurs these strange error.

**Comment by zixia** [comment] 2017-03-19 04:33
Ok. Then please make it posted to here when you noticed more details.

And there had an idea just jumped into my mind: why do not publish your TaskManager as an example bot? I believe this also could help others a lot. (like what @Gcaufy did)

**Comment by lijiarui** [comment] 2017-03-19 05:08
> Ok. Then please make it posted to here when you noticed more details, and more important: provide a procedure to reproduce it(in other servers).

I guess it maybe conflict with my mongodb, because after I use that without mongodb, it works well. But I'm not sure. I will try then to use the leatest code to reproduce it.

> And there had an idea just jumped into my mind: why do not publish your TaskManager as an example bot? I believe this also could help others a lot. (like what @Gcaufy did)

I'm refract all my code now, includes TaskManager, and I'm considering to change to [rabbitMQ](https://www.rabbitmq.com/)。 After I have a good solution about the queue, I will publish as an example bot.

**Comment by zixia** [comment] 2017-03-31 09:54
If you can not reproduce it, please close this issue.

Thanks.

**Closed** 2017-03-31 11:01 UTC
