### ISSUE TITLE
some strange session error

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#523] opened 2017-05-18 16:20 UTC
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
China
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
Tencent

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

```shell
root@tencent-juxiaomi:~/robot_ts# wechaty run doctor

 __        __        _           _
 \ \      / /__  ___| |__   __ _| |_ _   _
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
   \ V  V /  __/ (__| | | | (_| | |_| |_| |
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
                                     |___/
____________________________________________________
            https://www.wechaty.io
  ____                            _   _
 / ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _
| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
 \____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
                                              |___/
  ____ _           _   ____        _
 / ___| |__   __ _| |_| __ )  ___ | |_ ___
| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
| |___| | | | (_| | |_| |_) | (_) | |_\__ \
 \____|_| |_|\__,_|\__|____/ \___/ \__|___/


Starting Wechaty v0.7.73 with Node.js vv7.9.0 ...

> wechaty@0.7.73 doctor /wechaty
> npm run check-node-version && ts-node bin/doctor


> wechaty@0.7.73 check-node-version /wechaty
> check-node-version --node ">= 6.9"

node: 7.9.0
npm: 4.4.4
yarn: 0.22.0

  #### Wechaty Doctor

  1. Wechaty version: 0.7.73
  2. Linux x64 version 3.16.0-4-amd64 memory 245/1882 MB
  3. Docker: true
  4. Node version: v7.9.0
  5. Tcp IPC TEST: PASS
  6. Chromedriver: ChromeDriver 2.25 (5a911c1ac99b36efadff2041357740080cc27220)




 __        __        _           _
 \ \      / /__  ___| |__   __ _| |_ _   _
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
   \ V  V /  __/ (__| | | | (_| | |_| |_| |
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
                                     |___/
____________________________________________________
            https://www.wechaty.io
  _____      _ _      ___
 | ____|_  _(_) |_   / _ \
 |  _| \ \/ / | __| | | | |
 | |___ >  <| | |_  | |_| |
 |_____/_/\_\_|\__|  \___/

```

### Error log

```shell
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 3.16.0-4-amd64 x86_64)
08:14:45 WARN PuppetWebBridge proxyWechaty() exception: unknown error: bad inspector message: {"id":52040,"result":{"result":{"type":"object","value":{"status":0,"value":{"RemarkPYQuanPin":"","RemarkPYInitial":"","PYInitial":"SPANCLASSEMOJIEMOJI1F433SPANYXRSPANCLASSEMOJIEMOJI1F433SPAN","PYQuanPin":"spanclassemojiemoji1f433spanyouxinrenspanclassemojiemoji1f433span","Uin":0,"UserName":"@7f66c355275a568eafbd4c6f45fce487","NickName":"\u003Cimg class=\"emoji emoji1f433\" text=\"\uE054_web\" src=\"/zh_CN/htmledition/v2/images/spacer.gif\" /\u003E\u6709\u5FC3\u4EBA \u003Cimg class=\"emoji emoji1f433\" text=\"\uE054_web\" src=\"/zh_CN/htmledition/v2/images/spacer.gif\" /\u003E","HeadImgUrl":"/cgi-bin/mmwebwx-bin/webwxgeticon?seq=658933531&username=@7f66c355275a568eafbd4c6f45fce487&skey=@crypt_832129a3_f17d69aa8e132b8539aa1246f8a9fd92","ContactFlag":3,"MemberCount":0,"MemberList":[],"RemarkName":"","HideInputBarFlag":0,"Sex":1,"Signature":"\u003Cspan class=\"emoji emoji1f434\"\u003E\u003C/span\u003E\u6211\u5F00\u706B\u8F66\uFFFF","VerifyFlag":0,"OwnerUin":0,"StarFriend":0,"AppAccountFlag":0,"Statues":0,"AttrStatus":67229799,"Province":"","City":"","Alias":"","SnsFlag":49,"UniFriend":0,"DisplayName":"","ChatRoomId":0,"KeyWord":"eni","EncryChatRoomId":"","IsOwner":0,"MMOrderSymbol":"SPANCLASSEMOJIEMOJI1F433SPANYOUXINRENSPANCLASSEMOJIEMOJI1F433SPAN","_index":1609,"_h":50,"_offsetTop":80138,"stranger":false}}}}}
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 3.16.0-4-amd64 x86_64)
08:15:01 WARN PuppetWebBrowser execute() exception: unknown error: bad inspector message: {"id":52065,"result":{"result":{"type":"object","value":{"sta, WebDriverError: unknown error: bad inspector message: {"id":52065,"result":{"result":{"type":"object","value":{"status":0,"value":{"RemarkPYQuanPin":"","RemarkPYInitial":"","PYInitial":"SPANCLASSEMOJIEMOJI1F433SPANYXRSPANCLASSEMOJIEMOJI1F433SPAN","PYQuanPin":"spanclassemojiemoji1f433spanyouxinrenspanclassemojiemoji1f433span","Uin":0,"UserName":"@7f66c355275a568eafbd4c6f45fce487","NickName":"\u003Cimg class=\"emoji emoji1f433\" text=\"\uE054_web\" src=\"/zh_CN/htmledition/v2/images/spacer.gif\" /\u003E\u6709\u5FC3\u4EBA \u003Cimg class=\"emoji emoji1f433\" text=\"\uE054_web\" src=\"/zh_CN/htmledition/v2/images/spacer.gif\" /\u003E","HeadImgUrl":"/cgi-bin/mmwebwx-bin/webwxgeticon?seq=658933531&username=@7f66c355275a568eafbd4c6f45fce487&skey=@crypt_832129a3_f17d69aa8e132b8539aa1246f8a9fd92","ContactFlag":3,"MemberCount":0,"MemberList":[],"RemarkName":"","HideInputBarFlag":0,"Sex":1,"Signature":"\u003Cspan class=\"emoji emoji1f434\"\u003E\u003C/span\u003E\u6211\u5F00\u706B\u8F66\uFFFF","VerifyFlag":0,"OwnerUin":0,"StarFriend":0,"AppAccountFlag":0,"Statues":0,"AttrStatus":67229799,"Province":"","City":"","Alias":"","SnsFlag":49,"UniFriend":0,"DisplayName":"","ChatRoomId":0,"KeyWord":"eni","EncryChatRoomId":"","IsOwner":0,"MMOrderSymbol":"SPANCLASSEMOJIEMOJI1F433SPANYOUXINRENSPANCLASSEMOJIEMOJI1F433SPAN","_index":1609,"_h":50,"_offsetTop":80138,"stranger":false}}}}}
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 3.16.0-4-amd64 x86_64)
    at Object.checkLegacyResponse (/bot/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/bot/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/bot/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
08:15:01 WARN PuppetWebBridge execute() exception: unknown error: bad inspector message: {"id":52065,"result":{"result":{"type":"object","value":{"status":0,"value":{"RemarkPYQuanPin":"","RemarkPYInitial":"","PYInitial":"SPANCLASSEMOJIEMOJI1F433SPANYXRSPANCLASSEMOJIEMOJI1F433SPAN","PYQuanPin":"spanclassemojiemoji1f433spanyouxinrenspanclassemojiemoji1f433span","Uin":0,"UserName":"@7f66c355275a568eafbd4c6f45fce487","NickName":"\u003Cimg class=\"emoji emoji1f433\" text=\"\uE054_web\" src=\"/zh_CN/htmledition/v2/images/spacer.gif\" /\u003E\u6709\u5FC3\u4EBA \u003Cimg class=\"emoji emoji1f433\" text=\"\uE054_web\" src=\"/zh_CN/htmledition/v2/images/spacer.gif\" /\u003E","HeadImgUrl":"/cgi-bin/mmwebwx-bin/webwxgeticon?seq=658933531&username=@7f66c355275a568eafbd4c6f45fce487&skey=@crypt_832129a3_f17d69aa8e132b8539aa1246f8a9fd92","ContactFlag":3,"MemberCount":0,"MemberList":[],"RemarkName":"","HideInputBarFlag":0,"Sex":1,"Signature":"\u003Cspan class=\"emoji emoji1f434\"\u003E\u003C/span\u003E\u6211\u5F00\u706B\u8F66\uFFFF","VerifyFlag":0,"OwnerUin":0,"StarFriend":0,"AppAccountFlag":0,"Statues":0,"AttrStatus":67229799,"Province":"","City":"","Alias":"","SnsFlag":49,"UniFriend":0,"DisplayName":"","ChatRoomId":0,"KeyWord":"eni","EncryChatRoomId":"","IsOwner":0,"MMOrderSymbol":"SPANCLASSEMOJIEMOJI1F433SPANYOUXINRENSPANCLASSEMOJIEMOJI1F433SPAN","_index":1609,"_h":50,"_offsetTop":80138,"stranger":false}}}}}
```

**Comment by zixia** [comment] 2017-08-18 03:36
It seems caused by some problems inside Selenium/WebDriver.

Close it due to un-active for a long time.

**Closed by zixia** 2017-08-18 03:36 UTC
