### ISSUE TITLE
`login` event is absence after scan the QR Code. (with phantomjs head)

### ISSUE THREAD

**Issue by cmzz** [Chatie/wechaty#743] opened 2017-08-18 01:39 UTC
扫码，然后手机上确认，但是机器人却并没有登录(登录事件未触发)。

但是微信手机客户端却是显示web版已登录。

并不是每次都是这样，偶发。

使用 phantomsjs

有人遇到吗

**Comment by zixia** [comment] 2017-08-18 02:56
Hi cmzz, you are surprising me because I do not know the phantomjs could work in production. I'm not using it for a long time.

According to [[Announcement] Stepping down as maintainer](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE) from Vitaly Slobodin, the owner of PhantomJs, we'd better use headless chrome instead.

Please also see the headless Chrome implement discussion of Wechaty at here: #739 

You can use Wechaty with headless Chrome by set the env var `WECHATY_HEAD=chrome-headless`, and also make sure that you are using chrome version at least v62, which is in `UNSTABLE` stage.

**Comment by cmzz** [comment] 2017-08-18 15:45
每天被用户反馈微信登录不上啊（就是扫码后机器人没有登录）.  
今天我不得以又发布了一个版本，去掉了 phantomjs ，但是测试发现问题依然存在：

**即使不使用 phantomjs ，也会出现扫码确认后机器人没反应的情况，概率非常高。**

请问这是什么原因呢。

**Comment by cmzz** [comment] 2017-08-18 15:47
![image](https://user-images.githubusercontent.com/6111715/29466446-7e53ce64-846f-11e7-8b80-e026c244af68.png)

![image](https://user-images.githubusercontent.com/6111715/29466483-9c3b7aee-846f-11e7-8e72-95fc191858d3.png)

大概就是这样子的情况。

**Comment by cmzz** [comment] 2017-08-18 15:53
我的代码片段：
 ```
 static init () {
    log.info('wechaty init')
    this.bot = Wechaty.instance({
      // 'head': 'phantomjs'
    })
    this.registerHandler()
    Store.bot = this.bot

    log.info(this.bot)
    gl.info(`微信机器人初始化`)
  } 

...

this.bot
      .on('scan', (url, code) => {
        log.info(`${url}\n[${code}] Scan QR Code in above url to login: `)
        console.log(code)
        gl.info(`登录二维码: ${url}`)

        RendererWindow.get('wechatWindow').send('showWechatQrcode', {qr: url})
      })
```

下面这是没反应时的日志，Wechaty 初始化之后，打开扫码页面之后，事件没有触发：

```
[2017-08-18 23:26:28:0947] [info] Wechaty {
  domain: null,
  _events: 
   { scan: [Function],
     logout: [Function],
     login: [Function],
     message: [Function],
     friend: [Function],
     error: [Function] },
  _eventsCount: 6,
  _maxListeners: undefined,
  setting: { head: 'chrome', puppet: 'web', profile: null },
  state: 
   StateSwitch {
     _client: 'Wechaty',
     log: Brolog { enableTimestamp: true, logLevel: 3, prefixFilter: /.*/ },
     _target: 'standby',
     _current: 'standby',
     _stable: true },
  uuid: '34ee2f1c-f16b-4096-8300-fd284409b75b' }
```

下面是正常的日志：

```
[2017-08-18 23:28:39:0188] [info] Wechaty {
  domain: null,
  _events: 
   { scan: [Function],
     logout: [Function],
     login: [Function],
     message: [Function],
     friend: [Function],
     error: [Function] },
  _eventsCount: 6,
  _maxListeners: undefined,
  setting: { head: 'chrome', puppet: 'web', profile: null },
  state: 
   StateSwitch {
     _client: 'Wechaty',
     log: Brolog { enableTimestamp: true, logLevel: 3, prefixFilter: /.*/ },
     _target: 'standby',
     _current: 'standby',
     _stable: true },
  uuid: '9fb77ebc-80ce-4185-8078-189232a6384b' }
[2017-08-18 23:28:47:0794] [info] https://login.weixin.qq.com/qrcode/Ae7J4eo3EA==
[0] Scan QR Code in above url to login: 
```

有提示扫码，这事扫码才能成功的登录，前面的那种情况，扫码就无法登录。

概率非常之高啊。。求解决一下。

**Comment by cmzz** [comment] 2017-08-18 15:53
@zixia

**Comment by cmzz** [comment] 2017-08-19 01:11
如果不使用 phantomsjs ， 用户电脑是不是必须要安装 chroe 浏览器？ 或者能用 360 什么的替代吗？

**Comment by zixia** [comment] 2017-08-19 04:51
Could you please provide a minimum runnable code snip to reproduce the problem, with log output?

That would very helpful to let me see what happened with your system.

**Comment by zixia** [comment] 2017-08-21 07:18
Yes, the end user has to install chrome correctly. And currently, we support Chrome best so it's not recommended to install other browsers.

**Comment by zixia** [comment] 2017-08-26 10:09
Could you please confirm that your wechat account is not blocked out of WebWechat by Tencent? 

See #603

**Comment by zixia** [comment] 2017-08-26 10:51
Sorry for I'll close this issue for now because I decided that not support phantomjs anymore.

Please wait for the Chrome version 62 to be stable on 17 Oct 2017, then you can use chrome headless just as phantomjs did before.

**Closed by zixia** 2017-08-26 10:51 UTC
Labels: question
