### ISSUE TITLE
it seems RECALLED: 10002 message dose't trigger on('message') event

### ISSUE THREAD

**Issue by JasLin** [Chatie/wechaty#8] opened 2016-06-23 10:33 UTC
i tested the ding-dong-bot and recalled some message , it dose not trigger the event.

**Comment by zixia** [comment] 2016-06-27 14:00
Hi JasLin, 

when you run ding-dong-bot, there should be a `scan` event first, with the login qrcode url that you need to scan to login.

the `message` event will be emitted after login, at the time when you receive a new message.

**Comment by JasLin** [comment] 2016-06-28 07:21
@zixia  thanks for your reply , actually , i had use wechaty in my programs. i wrote a robot to serve some business, and everything is ok , but the when i recalled message from my wechat in mobile, it never trigger the message event . the test code is simple:

```
...
.on('message', m => {
  m.ready()
  .then(msg => {
    log.info('Bot', 'recv: %s', msg.toStringEx())
    logToFile(JSON.stringify(msg.rawObj))
    // test recalled message
    if(m.type() === Message.Type.RECALLED){
        console.log('recalled a message')
        m.dumpRaw()
    }
    ...
    
  })
  .catch(e => log.error('Bot', 'ready: %s' , e))
})
```

there is no message receive after recalled from mobile.

BTW: thanks for wechaty again, it may be the best wecaht sdk i have seen in github. i had move my code from python to javascript after compare with wechaty and some python wechat sdk .

**Comment by sjdy521** [comment] 2016-06-28 09:11
> it may be the best wecaht sdk i have seen in github
相当高的评价，我也赞一个

**Comment by zixia** [comment] 2016-06-28 09:37
@JasLin confirmed.

It seems the message of type `RECALLED` is not triggered in the current hook process. 

It must has other hook point of this type message, will figure it out when I has time.

at last, thanks for your review, I'd like to write it to README :) and thanks @sjdy521, too!

**Comment by zixia** [comment] 2016-11-12 05:42
@jaslin do u have any idea of how to fix this issue? i'm going to review it next week.

**Comment by JasLin** [comment] 2016-11-13 01:13
@zixia i haven't dig into this issue yet, this issue not so harmfull ,or i will going to see this next week too.

**Comment by zixia** [comment] 2016-11-14 17:15
About the RECALL Message behavior of `webwxApp`:

### Problem

1. RECALL Message does not like other messages:

  https://github.com/wechaty/webwx-app-tracker/blob/06ba28a762e4f13d1710962577afb53017d2190f/formatted/webwxApp.js#L2007

1. It `return` instead of call `addChatMessage()`:

  https://github.com/wechaty/webwx-app-tracker/blob/06ba28a762e4f13d1710962577afb53017d2190f/formatted/webwxApp.js#L2034

1. So there will no `message:add:success` broadcast event fired for RECALL Message:

  https://github.com/wechaty/webwx-app-tracker/blob/06ba28a762e4f13d1710962577afb53017d2190f/formatted/webwxApp.js#L1930

1. At last Wechaty will never get it.

### Solution

**Comment by zhaozhiming** [comment] 2017-04-11 13:40
Do the solutions above have not help?

**Comment by zixia** [comment] 2017-08-26 10:18
Close this issue because the PR will be merged soon.

**Closed by zixia** 2017-08-26 10:18 UTC
Labels: bug, enhancement, help wanted
