### ISSUE TITLE
[enhancement] handle room name change event

### ISSUE THREAD

**Issue by dcsan** [Chatie/wechaty#532] opened 2017-05-22 09:41 UTC
(low priority) feature request.

currently when a user changes the roomname, `ERROR unknown type Message` is returned.
it might be useful to trap this message in future.

```
ERROR unknown type Message {
  rawObj: 
   { MsgId: 'xxx',
     FromUserName: '@@xxx',
     ToUserName: '@xx',
     MsgType: 10000,
     Content: '你修改群名为“Bottesting2”',
     Status: 4,
     ImgStatus: 1,
     CreateTime: 1495445961,
     VoiceLength: 0,
     PlayLength: 0,
     FileName: '',
     FileSize: '',
     MediaId: '',
     Url: '',
     AppMsgType: 0,
     StatusNotifyCode: 0,
     StatusNotifyUserName: '',
     RecommendInfo: 
      { UserName: '',
        NickName: '',
        QQNum: 0,
        Province: '',
        City: '',
        Content: '',
        Signature: '',
        Alias: '',
        Scene: 0,
        VerifyFlag: 0,
        AttrStatus: 0,
        Sex: 0,
        Ticket: '',
        OpCode: 0 },
     ForwardFlag: 0,
     AppInfo: { AppID: '', Type: 0 },
     HasProductId: 0,
     Ticket: '',
     ImgHeight: 0,
     ImgWidth: 0,
     SubMsgType: 0,
     NewMsgId: xx,
     OriContent: '',
     MMPeerUserName: '@@xx',
     MMDigest: '你修改群名为“Bottesting2”',
     MMIsSend: false,
     MMIsChatRoom: true,
     LocalID: 'xx',
     ClientMsgId: 'xx',
     MMActualContent: '你修改群名为“Bottesting2”',
     MMActualSender: '@@xx',
     MMDigestTime: '9:39',
     MMDisplayTime: 1495445818,
     MMTime: '' },
  obj: 
   { id: 'xx',
     type: 10000,
     from: '@@xx',
     to: '@xx',
     content: '你修改群名为“Bottesting2”',
     status: 4,
     digest: '你修改群名为“Bottesting2”',
     date: 1495445818,
     url: undefined,
     room: '@@xx' },
  _counter: 9,
  id: 'xx' } +1ms
```

**Comment by zixia** [comment] 2017-05-22 12:28
Hi @dcsan , 

Could you provide the steps in details for producing the `ERROR unknown type Message`?

Thanks.

**Comment by dcsan** [comment] 2017-05-23 03:54
OK will do. wasn't sure if its a bug or just not supported yet as a feature.

**Comment by zixia** [comment] 2017-08-18 03:25
Close this issue due to not active for months.

Please feel free to reopen this issue if we can reproduce the problem.

**Closed by zixia** 2017-08-18 03:25 UTC
