### ISSUE TITLE
 Invalid audio output parameters received; using fake audio path.  

### ISSUE THREAD

**Issue by dongeast** [Chatie/wechaty#939] opened 2017-10-30 10:46 UTC
机器人跑的跑的，就出现这个日志了，如何解决？

[5952:4960:1030/014831.800:ERROR:audio_manager_base.c
c(275)] Invalid audio output parameters received; using fake audio path. Channel
s: 0, Sample Rate: 0, Bits Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/014844.798:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/014900.785:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/014909.769:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/014937.782:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/014944.783:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/015000.780:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/015059.779:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/015118.792:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/023250.063:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/061709.141:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/062113.054:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/063457.092:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/070449.167:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/073654.198:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/075056.157:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/075811.117:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/081813.191:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/082114.090:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/082713.141:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/084003.158:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/085648.224:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/090022.094:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/090340.165:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/090902.186:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/091435.163:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/091859.105:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/092604.188:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/092724.156:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/095216.205:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/095826.218:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/100114.105:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/101415.206:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/101841.152:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/102000.232:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/102556.232:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/103211.280:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/103445.092:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/105841.198:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/111253.297:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/113132.289:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/120505.275:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/120647.182:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/123125.288:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/124954.307:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/132039.317:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/132039.395:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/135448.365:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/135745.257:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/135834.143:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/140330.362:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/154929.410:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/155041.264:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/165249.535:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/170046.427:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0
[5952:4960:1030/174050.454:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0

**Comment by zixia** [comment] 2017-10-30 11:15
Sorry I have no idea about that because you did not provide any reproduce steps.

However, I'll push a commit that will mute the sound for chrome.

**Comment by dongeast** [comment] 2017-10-30 11:25
就是一直挂着，把微信群的聊天记录提交到API，这个log应该跟我写的代码没有关系。
我代码只是保存了类型为1和3的文本消息和图片消息，音频类信息直接忽略了。

这个audio你看是不是chrome driver的问题

**Comment by zixia** [comment] 2017-10-30 11:25
Sorry, we are not using any chrome driver anymore.

**Comment by dongeast** [comment] 2017-10-30 11:37
[6328:4120:1030/192905.992:ERROR:audio_manager_base.cc(275)] Invalid audio outpu
t parameters received; using fake audio path. Channels: 0, Sample Rate: 0, Bits
Per Sample: 0, Frames Per Buffer: 0

刚又报了这个log。我用一个微信往机器人的微信发了50多条文本信息，发现夹杂了这个log。我确定我没用audio

        // 忽略自己发的信息
        if (m.self()) {
            return
        }

        // 3	图片消息
        // 下载图片
        if (m.type() === 3) // MsgType.IMAGE
        {
            // if (m instanceof MediaMessage) {
                saveMediaFile(m);
            // }
            return
        }
        
        if (m.type()>1) {
            return
        }
会不会跟我注释了 if (m instanceof MediaMessage) { 有关系？ 
主要是instanceof我不知道如何引用，示例media-file-bot.js里我看
        if (m instanceof _1.MediaMessage) {
            saveMediaFile(m);
        }
const _1 = require("../");

我参考这个，instanceof还是会报错，不知道为啥，我就注释掉了

selenium-webdriver不是 chrome driver吗？

**Comment by dongeast** [comment] 2017-10-30 11:42
"rxjs": "^5.4", 升级为 "rxjs": "^5.5",

src/puppet-web/bridge.ts

+        '--audio-output-channels=0',
+        '--disable-default-apps',
+        '--disable-extensions',
+        '--disable-translate',

+        '--disable-sync',
+        '--hide-scrollbars',
+        '--mute-audio',

我看你做了这些修改，那我现在怎么办？直接取你的最新版，重新部署了跑吗？
主要是现在这个log会让我的bot挂掉退出

**The big question is what to do next.**

**Comment by zixia** [comment] 2017-10-30 13:47
I have no idea of what happened to you because I had never met this kind of issues.

The best suggestion that I could make is:
1. Go to read the code to understand what's happening. See: https://gitlab.com/fancycode/iridium-browser/blob/47d1474d116ffe95eb6d54bdce6b1c5f3e8fecc8/media/audio/audio_manager_base.cc
1. Join the wechaty community and discuss your issue with other developers.

Good luck.

**Comment by zixia** [comment] 2017-11-03 13:06
I'll close this issue because it's not related with Wechaty.

Please feel free to submit new issue if you have other issue.

**Closed by zixia** 2017-11-03 13:06 UTC
