### ISSUE TITLE
Sending Images

### ISSUE THREAD

**Issue by guilhermeprokisch** [Chatie/wechaty#690] opened 2017-07-26 02:40 UTC
Hi guys can you provide a example of how to send images? I trying to send by 

.say(new MediaMessage('image.jpg')) but I'm getting the error 

"(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Converting circular structure to JSON"

Thanks

**Comment by zixia** [comment] 2017-07-26 04:31
1. Please provide the shortest full code, which can reproduce your error.
1. See: <https://github.com/Chatie/wechaty/blob/master/example/ding-dong-bot.ts>

**Comment by binsee** [comment] 2017-08-10 09:32
Please refer to https://github.com/Chatie/wechaty/pull/714#issuecomment-321053235

**Comment by zixia** [comment] 2017-08-18 03:11
@guilhermeprokisch I'll close this issue because it should work without any problem.

Please let me know and I'll reopen it if you still have problems with sending images.

**Closed by zixia** 2017-08-18 03:11 UTC
