### ISSUE TITLE
ERR Profile save() exception: Error: EACCES: permission denied, open '/bot/demo.wechaty.json'

### ISSUE THREAD

**Issue by charlesluo2014** [Chatie/wechaty#982] opened 2017-11-22 13:51 UTC
### Provide Your Network Information

1. Where is the location of your server? (i.e. City, or In/Out China)
1. Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?

### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
wechaty run doctor

### Expected behavior
success

### Actual behavior

13:45:16 ERR Profile save() exception: Error: EACCES: permission denied, open '/bot/demo.wechaty.json'
(node:30) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EACCES: permission denied, open '/bot/demo.wechaty.json'
(node:30) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C13:45:19 INFO Bot finis(130, SIGINT)

### Full Output Logs

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```

<details>
<summary>
Show Logs
</summary>
### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:



```
</details>

**Comment by zixia** [comment] 2017-11-22 23:21
The error message is clear enough: ` Error: EACCES: permission denied`, which means you have not right to right to directory /bot

**Comment by Gcaufy** [comment] 2017-11-30 06:10
sudo chown 999.999 `pwd`

**Comment by zixia** [comment] 2017-11-30 06:27
Thanks @Gcaufy 

Confirmed, will look into it to see if we should go back to use root user as before.

**Comment by WeiFei365** [comment] 2017-12-13 02:06
@zixia did you fixed this exception? when i try to save the user's avatar, the docker will exit.  thanks a lot

**Comment by zixia** [comment] 2017-12-13 13:01
Not fix yet, because I'm still thinking about why I change to non-root user before...

It seems we should restore the docker to use the root user to make the life easier.

**Comment by Gcaufy** [comment] 2017-12-13 13:05
I agree, docker container they are independent, root should be safe for your host machine.

**Comment by zixia** [comment] 2017-12-13 14:49
@Gcaufy Ok, let's change it back to use root user.

Is there anyone who wants to make this PR? :)

**Comment by zixia** [comment] 2018-02-21 15:39
Will close this issue because I believe we had already switch back to use `root` inside our docker containers.

**Closed by zixia** 2018-02-21 15:39 UTC
Labels: bug
