### ISSUE TITLE
Get ECONNREFUSED when bot logout and cannot re-login

### ISSUE THREAD

**Issue by lijiarui** [Chatie/wechaty#617] opened 2017-06-28 09:48 UTC
When the bot run for a while, it logout and get the following error, then it cannot re-login again.

### Paste the full output logs here with `WECHATY_LOG=silly` set

```shell
$ WECHATY_LOG=silly npm run ts-node mybot.ts

# or 

$ WECHATY_LOG=silly node dist/mybot.js
```
<details>
<summary>
Show Logs
</summary>

### Paste the full output logs here with `WECHATY_LOG=silly` set

09:41:47 WARN PuppetWebBrowser execute() exception: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:40914, Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:40914
    at ClientRequest.<anonymous> (/wechaty/node_modules/selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
09:41:47 WARN PuppetWebBridge execute() exception: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:40914
09:41:47 WARN PuppetWebBridge proxyWechaty() noWechaty exception: Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:40914
    at ClientRequest.<anonymous> (/wechaty/node_modules/selenium-webdriver/http/index.js:238:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
</details>

**Comment by zixia** [comment] 2017-06-28 16:17
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by zixia** [comment] 2017-08-18 03:09
Close this issue due to not active for weeks.

**Closed by zixia** 2017-08-18 03:09 UTC
